ALTER TABLE banners ADD COLUMN showSearchBox BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE banners ADD COLUMN overlayOpacity INT NOT NULL DEFAULT 40;
ALTER TABLE banners ADD COLUMN linkTarget VARCHAR(20) NOT NULL DEFAULT '_self';
